runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/longear-FE/index.html
    upload: dist/loangear-FE/index.html
  - url: /
    static_dir: dist/loangear-FE
