runtime: python27
api_version: 1
threadsafe: yes

handlers:
  - url: /
    static_files: dist/loangear-FE/index.html
    upload: dist/loangear-FE/index.html
  - url: /
    static_dir: dist/loangear-FE

skip_files:
  - e2e/
  - node_modules/
  - src/
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE

env_variables:
  API_URL: "https://webapi-dev.appname.com"
